[environments]
  [environments.development]
    name = "node-test"
    namespace = "default"
    wait = false
    watch = false
    watch-delay = 2
    auto-connect = false
    override-ports = ["8080:8080", "9229:9229"]

